apps/blog/urls.py
from django.urls import path
from . import views
app_name = "blog"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('archives/', views.ArchivesView.as_view(), name='archives'),
    path('post/<int:pk>', views.article, name='article'),

    path('categories/', views.Categories.as_view(), name='categories'),
    path('category/<int:pk>', views.CategoryView.as_view(), name='category'),

    path('tags/', views.TagsView.as_view(), name='tags'),
    path('tag/<int:pk>', views.TagListView.as_view(), name='tag_list'),

    path('books/', views.BooksView.as_view(), name='books'),
    path('book_list/<int:pk>', views.BookListView.as_view(), name='book_list'),

    path('movies/', views.MoviesView.as_view(), name='movies'),
    path('movie_list/<int:pk>', views.MovieListView.as_view(), name='movie_list'),

    path('messages/', views.messages, name='messages'),

    path('download/', views.file_test, name='download'),


    # path('courses/', views.CoursesView.as_view(), name='courses'),
    # path('course/<int:pk>', views.course, name='course'),
    # path('course/article/<int:pk>', views.course_article, name='course_article'),
]

eastnotes/urls.py
import xadmin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from werobot.contrib.django import make_view
from . import views


urlpatterns = [
    path('admin/', xadmin.site.urls, name="admin"),
    path('', include('apps.blog.urls')),
    path('search/', include('haystack.urls')),
    path('mdeditor/', include('mdeditor.urls')),
    path('comment/', include('apps.comment.urls')),
    path('', include('apps.notice.urls')),
    path('', include('apps.myzone.urls')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

templates/movie/movie_list.html
{% extends "base.html" %}
{% load blog_tags %}

{% block meta %}
<title>当前分类：{{ tag_name }}-我的影单</title>
{% endblock %}

{% block content_left %}
    <div class="django-panel django-panel-padding">
        <h1 align="center">当前分类：{{ tag_name }}(共{{ lists | length }}部）</h1>
        <div class="django-card">
            {% for movie in lists %}
                    <div class="card col span_1_of_4" role="main">
                        <div class="card-item">
                            <div class="card-cover">
                                <div class="card-category">
                                    <a href="">{{ movie.category }}</a>
                                </div>
                                {% if movie.pid != "" %}
                                    <a href="{{ movie.get_absolute_url }}" target="_blank"><img class="thumb" alt="{{ movie.name }}" src="{% url 'blog:index' %}media/{{ movie.cover }}"></a>
                                {% else %}
                                    <img class="thumb" alt="{{ movie.name }}" src="{% url 'blog:index' %}media/{{ movie.cover }}">
                                {% endif %}
                            </div>

                            <div class="card-detail">
                                <h3>{{ movie.name }}</h3>
                                <p>豆瓣评分：{{ movie.score }}<br></p>
                                <p>观看时间：{{ movie.watch_time|date:"Y.m.d" }}</p>
                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block content_paginate %}
    {% if is_paginated %}
        <div class="django-panel django-pages">
            <ul class="pagination django-pages-ul">
                    <li><a href="?page=1"><span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span></a></li>

                    {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span></a></li>
                    {% else %}
                        <li><a href=""><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span></a></li>
                    {% endif %}

                    <li><span class="page-style" >{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span></li>

                    {% if page_obj.has_next %}
                        <li><a class="page-style" href="?page={{ page_obj.next_page_number }}"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a></li>
                    {% else %}
                        <li><span class="end-page-style page-style"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></span></li>
                    {% endif %}

                    <li><a class="page-style" href="?page={{ page_obj.paginator.num_pages }}"><span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span></a></li>
            </ul>
        </div>
    {% endif %}
{% endblock %}


{% block tag_sidebar %}
    <div class="sidebar" >
            <div class="title"><h3>热门标签</h3></div>
            <div class="git_tags">
                {% get_movies_tags as tags %}
                {% for tag in tags %}
                    <a href="{{ tag.get_absolute_url  }}" data-original-title="1304个话题">{{ tag.name }}</a>
                {% endfor %}
            </div>
    </div>
{% endblock %}

templates/movie/movies.html
{% extends "base.html" %}
{% load blog_tags %}


{% block meta %}
<title>我的影单</title>
{% endblock %}

{% block content_left %}
    <div class="django-panel django-panel-padding">
        <h1 align="center">我的影单(共{% get_total_movies %}部)</h1>
        <div class="django-card">
            {% for movie in lists %}
                    <div class="card col span_1_of_4" role="main">
                        <div class="card-item">
                            <div class="card-cover">
                                <div class="card-category">
                                    <a href="">{{ movie.category }}</a>
                                </div>
                                {% if movie.pid != "" %}
                                    <a href="{{ movie.get_absolute_url }}" target="_blank"><img alt="{{ movie.name }}" src="{% url 'blog:index' %}media/{{ movie.cover }}"></a>
                                {% else %}
                                    <img alt="{{ movie.name }}" src="{% url 'blog:index' %}media/{{ movie.cover }}">
                                {% endif %}
                            </div>

                            <div class="card-detail">
                                <h3>{{ movie.name }}</h3>
                                <p>豆瓣评分：{{ movie.score }}<br></p>
                                <p>观看时间：{{ movie.watch_time|date:"Y.m.d" }}</p>

                            </div>
                        </div>
                    </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}


{% block content_paginate %}
    {% if is_paginated %}
        <div class="django-panel django-pages">
            <ul class="pagination django-pages-ul">
                    <li><a href="?page=1"><span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span></a></li>

                    {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span></a></li>
                    {% else %}
                        <li><a href=""><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span></a></li>
                    {% endif %}

                    <li><span class="page-style" >{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span></li>

                    {% if page_obj.has_next %}
                        <li><a class="page-style" href="?page={{ page_obj.next_page_number }}"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></a></li>
                    {% else %}
                        <li><span class="end-page-style page-style"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></span></li>
                    {% endif %}

                    <li><a class="page-style" href="?page={{ page_obj.paginator.num_pages }}"><span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span></a></li>
            </ul>
        </div>
    {% endif %}
{% endblock %}



{% block tag_sidebar %}
    <div class="sidebar" >
            <div class="title"><h3>热门标签</h3></div>
            <div class="git_tags">
                {% get_movies_tags as tags %}
                {% for tag in tags %}
                    <a href="{{ tag.get_absolute_url  }}" data-original-title="1304个话题">{{ tag.name }}</a>
                {% endfor %}
            </div>
    </div>
{% endblock %}