apps/notice/urls.py
from django.urls import path
from . import views

app_name = "notice"

urlpatterns = [
    path('my_notifications/', views.my_notifications, name="my_notifications"),
    path('my_notification/<int:my_notifications_pk>', views.my_notification, name="my_notification"),
    path('delete_my_read_notifications', views.delete_my_read_notifications, name="delete_my_read_notifications"),
]

eastnotes/urls.py
import xadmin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from werobot.contrib.django import make_view
from . import views


urlpatterns = [
    path('admin/', xadmin.site.urls, name="admin"),
    path('', include('apps.blog.urls')),
    path('search/', include('haystack.urls')),
    path('mdeditor/', include('mdeditor.urls')),
    path('comment/', include('apps.comment.urls')),
    path('', include('apps.notice.urls')),
    path('', include('apps.myzone.urls')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

apps/notice/models.py
from django.db import models

# Create your models here.

apps/notice/views.py
from notifications.models import Notification
from django.shortcuts import render, redirect, reverse, get_object_or_404


# 消息通知页面
def my_notifications(request):
    context = {}
    return render(request, 'notice/my_notifications.html', context)


# 未读变已读，跳转至消息添加页面
def my_notification(request, my_notifications_pk):
    my_notification = get_object_or_404(Notification, pk=my_notifications_pk)
    my_notification.unread = False
    my_notification.save()
    return redirect(my_notification.data['url'])


# 删除全部已读
def delete_my_read_notifications(request):
    notifications = request.user.notifications.read()
    notifications.delete()
    return redirect(reverse('notice:my_notifications'))

templates/notice/my_notifications.html
{% extends "base.html" %}
{% load blog_tags %}


{% block meta %}
<title>我的消息</title>
{% endblock %}

{% block content_left %}
    <div class="django-panel django-panel-padding">
        <div class="messages">
            <a class="btn btn-primary" href="{% url 'notifications:mark_all_as_read'%}?next={% url 'notice:my_notifications' %}">全部设为已读</a>
            <a class="btn btn-danger" href="{% url 'notice:delete_my_read_notifications' %}">删除已读消息</a><br>
            {% for notification in request.user.notifications.all %}
                <ul class="notification">
                    <li class="{% if not notification.unread %}read{% endif %}">
                        ({{ notification.timesince }}之前)
                        <a href="{% url 'notice:my_notification'  notification.pk %}">{{ notification.verb }}</a>
                    </li>
                </ul>
            {% empty %}
                <li class="notification">暂时没有消息</li>
            {% endfor %}
        </div>
    </div>
{% endblock %}